#!/bin/sh
############################################################ IDENT(1)
#
# $Title: smite test for redis $
# $Copyright: 2013-2018 Smule, Inc. All rights reserved. $
# $Copyright: 2018 The FrauBSD Project. All rights reserved. $
# $FrauBSD: smite/redistest 2018-07-04 00:19:21 +0000 freebsdfrau $
#
############################################################ CONFIGURATION

INIT_PORT=6379
LAST_PORT=$INIT_PORT

############################################################ MAIN

case "$1" in
stop) # Promote slave to master
	cmd="slaveof no one" ;;
"") # Local redis test
	cmd="ping" ;;
*) # Remote redis test
	cmd="-h $1 ping"
esac

i=$INIT_PORT
while [ $i -le $LAST_PORT ]; do
	redis-cli -p $i $cmd > /dev/null 2>&1 ||
		[ "$cmd" = "slaveof no one" ] || exit 1
	i=$(( $i + 1 ))
done
exit 0

################################################################################
# END
################################################################################
